branches:
  - master
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'angular'
      releaseRules:
        - type: 'docs'
          scope: 'README'
          release: 'minor'
        - type: 'refactor'
          release: 'patch'
        - type: 'chore'
          release: 'patch'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: echo "Version=${nextRelease.version}" >> $GITHUB_ENV
